# Generated by Django 4.2.7 on 2026-07-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_company_taxation_form_ryczalt_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyrole',
            name='can_manage_accounting',
            field=models.BooleanField(default=False, help_text='Adnotacje kosztowe — opisywanie faktur i projekty kosztowe'),
        ),
        migrations.AlterField(
            model_name='companyrole',
            name='can_manage_inventory',
            field=models.BooleanField(default=False, help_text='Inwentaryzacja — dokumenty INW'),
        ),
        migrations.AlterField(
            model_name='companyrole',
            name='can_manage_products',
            field=models.BooleanField(default=False, help_text='Produkty — katalog produktów i ceny'),
        ),
        migrations.AlterField(
            model_name='companyrole',
            name='can_manage_warehouses',
            field=models.BooleanField(default=False, help_text='Magazyny — zarządzanie magazynami'),
        ),
    ]
