# Generated by Django 4.2.7 on 2026-07-19 09:02

import apps.users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_companymodule_module_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.users.models.NullableEmailUserManager()),
            ],
        ),
    ]
