# Generated by Django 4.2.7 on 2026-07-19 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='activity_ac_company_a12d03_idx',
            old_name='activity_co_created_idx',
        ),
    ]
