# Generated by Django 4.2.7 on 2026-07-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksef', '0010_receivedksefinvoice_original_ksef_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivedksefinvoice',
            name='original_ksef_number',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
